InitialPlatformCount: 12
PlatformMinimumWidth: 1.0
PlatformHeight: 1.0
PlatformTextureSize: [192, 128]

# Texture Information
PlatformFaceXNeg:
  Texture: "Editor/panel.jpg"
  DestinationPixel: [0, 0]
PlatformFaceXPos:
  Texture: "Editor/panel.jpg"
  DestinationPixel: [64, 0]
PlatformFaceYNeg:
  Texture: "Editor/silver.jpg"
  DestinationPixel: [128, 0]
PlatformFaceYPos:
  Texture: "Editor/silver.jpg"
  DestinationPixel: [0, 64]
PlatformFaceZNeg:
  Texture: "Editor/panel.jpg"
  DestinationPixel: [64, 64]
PlatformFaceZPos:
  Texture: "Editor/panel.jpg"
  DestinationPixel: [128, 64]
