InitialPlatformCount: 12
PlatformMinimumWidth: 1.0
PlatformHeight: 1.0
PlatformTextureSize: [768, 512]

# Texture Information
PlatformFaceXNeg:
  Texture: "Editor/wall_010.png"
  DestinationPixel: [0, 0]
PlatformFaceXPos:
  Texture: "Editor/wall_010.png"
  DestinationPixel: [256, 0]
PlatformFaceYNeg:
  Texture: "Editor/wall_010.png"
  DestinationPixel: [512, 0]
PlatformFaceYPos:
  Texture: "Editor/floor_003.png"
  DestinationPixel: [0, 256]
PlatformFaceZNeg:
  Texture: "Editor/wall_010.png"
  DestinationPixel: [256, 256]
PlatformFaceZPos:
  Texture: "Editor/wall_010.png"
  DestinationPixel: [512, 256]
